### ISSUE TITLE
Android 11 播放视频动画提示解码失败

### ISSUE THREAD

**Issue by wenluoLi** [Tencent/vap#105]
# issue 模版

1. 问题描述（重现路径）

- 同时播放视频流+视频动画，必现解码异常；同样条件下，只播放视频动画无异常

2. 运行环境（手机型号，Android/iOS版本等）
- 小米 11 ， 系统：Android 11
3. 相关日志

- MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 5

**Comment by hexleo** [comment]
麻烦给下出问题的mp4素材，是否能在vap的demo里复现下问题，这样我才好查

**Comment by Felix1030** [comment]
Google Piexl 4 Android11 demo 除了特殊的size可以播放 其他全部出现NPE

`2021-08-02 10:21:02.798 11344-11561/? E/AnimPlayer.HardDecoder: MediaCodec exception e=java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at android.media.MediaFormat.getInteger(MediaFormat.java:1283)
        at com.tencent.qgame.animplayer.HardDecoder.startDecode(HardDecoder.kt:231)
        at com.tencent.qgame.animplayer.HardDecoder.access$startDecode(HardDecoder.kt:29)
        at com.tencent.qgame.animplayer.HardDecoder$startPlay$$inlined$apply$lambda$1.run(HardDecoder.kt:169)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-08-02 10:21:02.798 11344-11561/? E/AnimPlayer.Decoder: onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
2021-08-02 10:21:02.798 11344-11561/? I/AnimSimpleDemoActivity: onFailed errorType=10002 errorMsg=0x2 MediaCodec exception e=java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference`

**Comment by hexleo** [comment]
更新带最新的Android2.0.19，这是之前一个bug，已经修复 #
