### ISSUE TITLE
在Dialog中播放vap报错

### ISSUE THREAD

**Issue by yangyang10** [Tencent/vap#161]
1. 问题描述  在Dialog中无法播放vap特效，在activity中正常
2. 运行环境   Android
3. 相关日志
java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at android.view.TextureView.setBackgroundDrawable(TextureView.java:331)
        at android.view.View.setBackground(View.java:22928)
        at android.view.View.<init>(View.java:5802)
        at android.view.View.<init>(View.java:5200)
        at android.view.TextureView.<init>(TextureView.java:168)
        at com.tencent.qgame.animplayer.textureview.InnerTextureView.<init>(InnerTextureView.kt:11)
        at com.tencent.qgame.animplayer.textureview.InnerTextureView.<init>(InnerTextureView.kt:10)
        at com.tencent.qgame.animplayer.AnimView$prepareTextureView$1.run(AnimView.kt:105)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by hexleo** [comment]
![image](https://user-images.githubusercontent.com/3285051/139615592-5e0a4a72-0dd6-4a01-b827-03369129c243.png)

**Comment by yangyang10** [comment]
找到了是在style中设置了 <item name="android:background">@android:color/transparent</item>
