### ISSUE TITLE
DialogFragment中使用出现crash

### ISSUE THREAD

**Issue by 846825177** [Tencent/vap#212]
java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at android.view.TextureView.setBackgroundDrawable(TextureView.java:321)
        at android.view.View.setBackground(View.java:21899)
        at android.view.View.<init>(View.java:5554)
        at android.view.View.<init>(View.java:4967)
        at android.view.TextureView.<init>(TextureView.java:161)
        at com.tencent.qgame.animplayer.textureview.InnerTextureView.<init>(InnerTextureView.kt:11)
        at com.tencent.qgame.animplayer.textureview.InnerTextureView.<init>(InnerTextureView.kt:9)
        at com.tencent.qgame.animplayer.AnimView.prepareTextureViewRunnable$lambda-1(AnimView.kt:104)
        at com.tencent.qgame.animplayer.AnimView.lambda$r69b_0_73RU0leBtt9RIdCotl9A(Unknown Source:0)
        at com.tencent.qgame.animplayer.-$$Lambda$AnimView$r69b_0_73RU0leBtt9RIdCotl9A.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7779)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)

**Comment by hexleo** [comment]
你可以检查下你的布局文件，或默认style设置，这里应该是给Dialog设置了默认的style，而且style里有设置背景，TextureView不能设置背景，所以会出现crash.
