### ISSUE TITLE
surface 没有主动释放

### ISSUE THREAD

**Issue by soloong** [Tencent/vap#255]
Caused by: java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at android.view.Surface.setNativeObjectLocked(Surface.java:667)
        at android.view.Surface.<init>(Surface.java:243)
        at com.tencent.qgame.animplayer.EGLUtil.start(EGLUtil.kt:49)
        at com.tencent.qgame.animplayer.Render.<init>(Render.kt:50)
        at com.tencent.qgame.animplayer.Decoder.prepareRender(Decoder.kt:94)
        at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:126)
        at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
        at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:57)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by hexleo** [comment]
是否能提供更详细的信息，比如机型，android版本，是否必现，复现路径

**Comment by soloong** [comment]
复现步骤：

一、开启严格模式
启动PlayerFragment ，使用VAP播放视频，不用关闭页面.

二、日志现象
 
 （1）出现前触发了gc
08-10 11:57:31.071 17487 25552 I app进程: NativeAlloc concurrent copying GC freed 105675(5529KB) AllocSpace objects, 30(1572KB) LOS objects, 49% free, 13MB/26MB, paused 134us total 102.551ms
08-10 11:57:31.071 17487 25799 I app进程: WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 74.849ms
（2）接着PlayerBase: baseRelease() piid=46711 state=0 之后出现，StrictMode检测到泄露
（3）出现泄露的时候，onVideoRender一直在回调，仍然在继续

三、目前使用的vap版本
2.0.25

四、其他现象
（1）部分机型上会出现绿屏，不知道是不是这个问题引起的
（2）目前我手中的机型，荣耀pad（JKR-W09)、小度T10都出现了，应该是必现

**Comment by soloong** [comment]
感觉在一直不断的创建Surface，同时释放不是主动调用的

**Comment by soloong** [comment]
看日志是创建2个Surface，都没有主动释放

08-10 11:57:31.090 17487 25554 D StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.view.Surface.finalize(Surface.java:259)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at java.lang.Daemons$Daemon.run(Daemons.java:137)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at java.lang.Thread.run(Thread.java:929)
08-10 11:57:31.090 17487 25554 D StrictMode: Caused by: java.lang.Throwable: Explicit termination method 'release' not called
08-10 11:57:31.090 17487 25554 D StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:237)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.view.Surface.setNativeObjectLocked(Surface.java:667)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.view.Surface.<init>(Surface.java:243)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.EGLUtil.start(EGLUtil.kt:49)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.Render.<init>(Render.kt:50)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.Decoder.prepareRender(Decoder.kt:94)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:126)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:57)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.os.Handler.handleCallback(Handler.java:900)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:103)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.os.Looper.loop(Looper.java:219)
08-10 11:57:31.090 17487 25554 D StrictMode: 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-10 11:57:31.091 17487 26983 E kg catched error: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
08-10 11:57:31.091 17487 25554 D StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.view.Surface.finalize(Surface.java:259)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at java.lang.Daemons$Daemon.run(Daemons.java:137)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at java.lang.Thread.run(Thread.java:929)
08-10 11:57:31.091 17487 25554 D StrictMode: Caused by: java.lang.Throwable: Explicit termination method 'release' not called
08-10 11:57:31.091 17487 25554 D StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:237)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.view.Surface.setNativeObjectLocked(Surface.java:667)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.view.Surface.<init>(Surface.java:243)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:163)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:57)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.os.Handler.handleCallback(Handler.java:900)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:103)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.os.Looper.loop(Looper.java:219)
08-10 11:57:31.091 17487 25554 D StrictMode: 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by hexleo** [comment]
感谢反馈，在2.0.27解决

**Comment by barryly** [comment]
用了最新的修改还是有这个问题 @hexleo 
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                                    java.lang.Throwable: Explicit termination method 'release' not called
                                                                                                    	at dalvik.system.CloseGuard.open(CloseGuard.java:223)
                                                                                                    	at android.view.Surface.setNativeObjectLocked(Surface.java:615)
                                                                                                    	at android.view.Surface.<init>(Surface.java:194)
                                                                                                    	at com.tencent.qgame.animplayer.EGLUtil.start(EGLUtil.kt:49)
                                                                                                    	at com.tencent.qgame.animplayer.Render.<init>(Render.kt:50)
                                                                                                    	at com.tencent.qgame.animplayer.Decoder.prepareRender(Decoder.kt:94)
                                                                                                    	at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:126)
                                                                                                    	at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
                                                                                                    	at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:192)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)
