### ISSUE TITLE
特定手机文件解析失败10002错误

### ISSUE THREAD

**Issue by Qiang11** [Tencent/vap#267]
版本 2.0.24
手机  一加9rt ，其他手机正常
素材  https://im-italker.oss-cn-hangzhou.aliyuncs.com/love_in_hand.mp4
错误日志：com.tencent.qgame.playerproj E/AnimPlayer.HardDecoder: MediaCodec configure exception e=java.lang.IllegalArgumentException
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2176)
        at android.media.MediaCodec.configure(MediaCodec.java:2092)
        at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:163)
        at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
        at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-09-29 12:09:34.538 4831-6352/com.tencent.qgame.playerproj E/AnimPlayer.Decoder: onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=java.lang.IllegalArgumentException

**Comment by hexleo** [comment]
能不能补充完整的播放日志，不止是错误堆栈。看你用的版本2.0.24，你升级看看，之前解过几个crash的问题

**Comment by Qiang11** [comment]
2022-09-29 14:33:19.065 26163-26921/com.tencent.qgame.playerproj I/AnimPlayer.HardDecoder: Video size is 96 x 64
2022-09-29 14:33:19.065 26163-26921/com.tencent.qgame.playerproj I/AnimPlayer.Decoder: prepareRender
2022-09-29 14:33:19.067 26163-26921/com.tencent.qgame.playerproj I/AnimPlayer.AnimPluginManager: onRenderCreate
2022-09-29 14:33:19.067 26163-26921/com.tencent.qgame.playerproj I/AnimPlayer.MaskAnimPlugin: mask render init
2022-09-29 14:33:19.068 26163-26923/com.tencent.qgame.playerproj E/AnimPlayer.AudioPlayer: cannot find audio track
2022-09-29 14:33:19.069 26163-26921/com.tencent.qgame.playerproj I/AnimPlayer.HardDecoder: Video MIME is video/avc
2022-09-29 14:33:19.070 26163-26921/com.tencent.qgame.playerproj D/MediaCodecList: codecHandlesFormat: no format, so no extra checks
2022-09-29 14:33:19.070 26163-26921/com.tencent.qgame.playerproj D/MediaCodecList: codecHandlesFormat: no format, so no extra checks
2022-09-29 14:33:19.070 26163-26921/com.tencent.qgame.playerproj D/MediaCodecList: codecHandlesFormat: no format, so no extra checks
2022-09-29 14:33:19.071 26163-26921/com.tencent.qgame.playerproj D/OplusCCodec: OplusCCodec [122]: (0x7d63da8780)
2022-09-29 14:33:19.071 26163-26921/com.tencent.qgame.playerproj W/libc: Access denied finding property "vendor.oplus.media.vpp.stutter"
2022-09-29 14:33:19.072 26163-26926/com.tencent.qgame.playerproj D/CCodec: allocate(c2.qti.avc.decoder)
2022-09-29 14:33:19.076 26163-26926/com.tencent.qgame.playerproj I/CCodec: setting up 'default' as default (vendor) store
2022-09-29 14:33:19.087 26163-26926/com.tencent.qgame.playerproj I/CCodec: Created component [c2.qti.avc.decoder]
2022-09-29 14:33:19.087 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: read media type: video/avc
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_dpb_luma
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_dpb_chroma
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_opb_luma
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_opb_chroma
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_dpb_luma
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_dpb_chroma
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_opb_luma
2022-09-29 14:33:19.088 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_opb_chroma
2022-09-29 14:33:19.089 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: ignored struct field vendor.qti-ext-dec-panscan.window
2022-09-29 14:33:19.092 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
2022-09-29 14:33:19.092 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: ignoring local param raw.size (0xd2001800) as it is already supported
2022-09-29 14:33:19.092 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: ignoring local param default.color (0x5200180b) as it is already supported
2022-09-29 14:33:19.093 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: ignoring local param raw.hdr-static-info (0xd200180a) as it is already supported
2022-09-29 14:33:19.093 26163-26926/com.tencent.qgame.playerproj I/CCodecConfig: query failed after returning 17 values (BAD_INDEX)
2022-09-29 14:33:19.093 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: c2 config diff is Dict {
      c2::i32 algo.priority.value = 0
      c2::float algo.rate.value = 30
      c2::u32 algo.secure-mode.value = 0
      c2::float coded.frame-rate.value = 30
      c2::u32 coded.pl.level = 0
      c2::u32 coded.pl.profile = 20484
      c2::u32 coded.vui.color.matrix = 255
      c2::u32 coded.vui.color.primaries = 0
      c2::u32 coded.vui.color.range = 0
      c2::u32 coded.vui.color.transfer = 255
      c2::u32 default.color.matrix = 0
      c2::u32 default.color.primaries = 0
      c2::u32 default.color.range = 0
      c2::u32 default.color.transfer = 0
      c2::u32 input.buffers.max-size.value = 7077888
      c2::u32 input.delay.value = 0
      string input.media-type.value = "video/avc"
      c2::u32 output.delay.value = 8
      string output.media-type.value = "video/raw"
      c2::u32 raw.color.matrix = 255
      c2::u32 raw.color.primaries = 0
      c2::u32 raw.color.range = 0
      c2::u32 raw.color.transfer = 255
      c2::float raw.hdr-static-info.mastering.blue.x = 0
      c2::float raw.hdr-static-info.mastering.blue.y = 0
      c2::float raw.hdr-static-info.mastering.gre
2022-09-29 14:33:19.093 26163-26926/com.tencent.qgame.playerproj W/ColorUtils: expected specified color aspects (0:0:255:255)
2022-09-29 14:33:19.095 26163-26921/com.tencent.qgame.playerproj I/MediaCodec: [c2.qti.avc.decoder] configure, format : AMessage(what = 0x00000000) = {
      int32_t max-bitrate = 2000000
      int32_t track-id = 1
      int32_t level = 2048
      string mime = "video/avc"
      int32_t frame-count = 49
      int32_t profile = 2
      int32_t bitrate = 645198
      string language = "und"
      int32_t display-width = 96
      Buffer csd-1 = {
        00000000:  00 00 00 01 68 eb cc b2                           ....h...
      }
      int64_t durationUs = 816666
      int32_t display-height = 64
      int32_t width = 96
      int32_t max-input-size = 3081
      int32_t frame-rate = 60
      int32_t height = 64
      Buffer csd-0 = {
        00000000:  00 00 00 01 67 4d 40 28  d9 06 26 84 00 00 03 00  ....gM@(..&.....
        00000010:  04 00 00 03 01 e0 3c 60  c9 20                    ......<`. 
      }
    }
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj D/SurfaceUtils: connecting to surface 0x7d63c2f810, reason connectToSurface
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj I/MediaCodec: [c2.qti.avc.decoder] setting surface generation to 26790914
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj D/SurfaceUtils: disconnecting from surface 0x7d63c2f810, reason connectToSurface(reconnect)
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj D/SurfaceUtils: connecting to surface 0x7d63c2f810, reason connectToSurface(reconnect)
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid module:sr-osie-whitelist uid:10486 cost 170us return (null)
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj D/OplusCCodec: debug enabled , debugType :0
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj D/OplusCCodec: [initiateConfigureComponent:L328] OplusFeedbackInfo  mFeedbackID:538546177920
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid pid:26163 procName: cost 81us return -1
2022-09-29 14:33:19.095 26163-26925/com.tencent.qgame.playerproj D/AtlasEventUploadUtils: setEvent event:atlas_event_video_monitor_network_switch
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid start module:check-first-IRAP uid:10486  time 607527142708us
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid end module:check-first-IRAP uid:10486  time 607527142783us
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj D/ListServiceUtils: checkInListByUid module:check-first-IRAP uid:10486 cost 74us return 0
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid start module:notify-network-optimize uid:10486  time 607527142801us
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid end module:notify-network-optimize uid:10486  time 607527142848us
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj D/ListServiceUtils: checkInListByUid module:notify-network-optimize uid:10486 cost 46us return 0
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid start module:video-statistics uid:10486  time 607527142857us
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj V/ListServiceUtils: checkInListByUid end module:video-statistics uid:10486  time 607527142900us
2022-09-29 14:33:19.096 26163-26925/com.tencent.qgame.playerproj D/ListServiceUtils: checkInListByUid module:video-statistics uid:10486 cost 43us return 0
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodec: [c2.qti.avc.decoder] buffers are bound to CCodec for this session
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for track-id
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for frame-count
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for language
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for display-width
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for csd-1
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for durationUs
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for display-height
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for native-window
2022-09-29 14:33:19.096 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: no c2 equivalents for flags
2022-09-29 14:33:19.097 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: Bad parameter value
2022-09-29 14:33:19.097 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: c2 config diff is   c2::float coded.frame-rate.value = 60
      c2::u32 coded.pl.level = 20491
      c2::u32 coded.pl.profile = 20482
      c2::u32 raw.size.width = 96
2022-09-29 14:33:19.097 26163-26926/com.tencent.qgame.playerproj W/CCodec: failed to configure c2 params
2022-09-29 14:33:19.098 26163-26925/com.tencent.qgame.playerproj E/MediaCodec: Codec reported err 0xffffffea, actionCode 0, while in state 3/CONFIGURING
2022-09-29 14:33:19.098 26163-26925/com.tencent.qgame.playerproj D/SurfaceUtils: disconnecting from surface 0x7d63c2f810, reason disconnectFromSurface
2022-09-29 14:33:19.098 26163-26921/com.tencent.qgame.playerproj E/MediaCodec: configure failed with err 0xffffffea, resetting...
2022-09-29 14:33:19.098 26163-26925/com.tencent.qgame.playerproj D/OplusCCodec: initiateShutdown [386]: (0x7d63da8780) keepComponentAllocated=0
2022-09-29 14:33:19.098 26163-26925/com.tencent.qgame.playerproj I/OplusFeedbackInfo: [sendFeedbackInfo:L303]  send:MM_FB_EventID#21001#ClientPid#26163#ReportLevel#0#timeUsage#0#videoBitRate#645198#videoComponent#c2.qti.avc.decoder#videoFrameRate#60#videoHeight#64#videoLevel#2048#videoMime#video/avc#videoProfile#2#videoWidth#96
2022-09-29 14:33:19.098 26163-26925/com.tencent.qgame.playerproj D/AtlasEventUploadUtils: setEvent event:atlas_event_atlasserver_feedback
2022-09-29 14:33:19.099 26163-26926/com.tencent.qgame.playerproj I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2022-09-29 14:33:19.100 26163-26921/com.tencent.qgame.playerproj D/OplusCCodec: ~OplusCCodec [137]: (0x7d63da8780)
2022-09-29 14:33:19.101 26163-26921/com.tencent.qgame.playerproj D/OplusCCodec: OplusCCodec [122]: (0x7d63da8780)
2022-09-29 14:33:19.101 26163-26921/com.tencent.qgame.playerproj W/libc: Access denied finding property "vendor.oplus.media.vpp.stutter"
2022-09-29 14:33:19.101 26163-26921/com.tencent.qgame.playerproj D/AtlasEventUploadUtils: setEvent event:atlas_event_video_monitor_network_switch
2022-09-29 14:33:19.101 26163-26926/com.tencent.qgame.playerproj D/CCodec: allocate(c2.qti.avc.decoder)
2022-09-29 14:33:19.103 26163-26926/com.tencent.qgame.playerproj I/CCodec: setting up 'default' as default (vendor) store
2022-09-29 14:33:19.113 26163-26926/com.tencent.qgame.playerproj I/CCodec: Created component [c2.qti.avc.decoder]
2022-09-29 14:33:19.113 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: read media type: video/avc
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_dpb_luma
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_dpb_chroma
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_opb_luma
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_opb_chroma
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_dpb_luma
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_dpb_chroma
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_opb_luma
2022-09-29 14:33:19.115 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_opb_chroma
2022-09-29 14:33:19.116 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: ignored struct field vendor.qti-ext-dec-panscan.window
2022-09-29 14:33:19.118 26163-26926/com.tencent.qgame.playerproj D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
2022-09-29 14:33:19.118 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: ignoring local param raw.size (0xd2001800) as it is already supported
2022-09-29 14:33:19.118 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: ignoring local param default.color (0x5200180b) as it is already supported
2022-09-29 14:33:19.118 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: ignoring local param raw.hdr-static-info (0xd200180a) as it is already supported
2022-09-29 14:33:19.119 26163-26926/com.tencent.qgame.playerproj I/CCodecConfig: query failed after returning 17 values (BAD_INDEX)
2022-09-29 14:33:19.119 26163-26926/com.tencent.qgame.playerproj D/CCodecConfig: c2 config diff is Dict {
      c2::i32 algo.priority.value = 0
      c2::float algo.rate.value = 30
      c2::u32 algo.secure-mode.value = 0
      c2::float coded.frame-rate.value = 30
      c2::u32 coded.pl.level = 0
      c2::u32 coded.pl.profile = 20484
      c2::u32 coded.vui.color.matrix = 255
      c2::u32 coded.vui.color.primaries = 0
      c2::u32 coded.vui.color.range = 0
      c2::u32 coded.vui.color.transfer = 255
      c2::u32 default.color.matrix = 0
      c2::u32 default.color.primaries = 0
      c2::u32 default.color.range = 0
      c2::u32 default.color.transfer = 0
      c2::u32 input.buffers.max-size.value = 7077888
      c2::u32 input.delay.value = 0
      string input.media-type.value = "video/avc"
      c2::u32 output.delay.value = 8
      string output.media-type.value = "video/raw"
      c2::u32 raw.color.matrix = 255
      c2::u32 raw.color.primaries = 0
      c2::u32 raw.color.range = 0
      c2::u32 raw.color.transfer = 255
      c2::float raw.hdr-static-info.mastering.blue.x = 0
      c2::float raw.hdr-static-info.mastering.blue.y = 0
      c2::float raw.hdr-static-info.mastering.gre
2022-09-29 14:33:19.119 26163-26926/com.tencent.qgame.playerproj W/ColorUtils: expected specified color aspects (0:0:255:255)
2022-09-29 14:33:19.120 26163-26921/com.tencent.qgame.playerproj E/AnimPlayer.HardDecoder: MediaCodec configure exception e=java.lang.IllegalArgumentException
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2176)
        at android.media.MediaCodec.configure(MediaCodec.java:2092)
        at com.tencent.qgame.animplayer.HardDecoder.startPlay(HardDecoder.kt:163)
        at com.tencent.qgame.animplayer.HardDecoder.access$startPlay(HardDecoder.kt:29)
        at com.tencent.qgame.animplayer.HardDecoder$start$1.run(HardDecoder.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-09-29 14:33:19.120 26163-26921/com.tencent.qgame.playerproj E/AnimPlayer.Decoder: onFailed errorType=10002, errorMsg=0x2 MediaCodec exception e=java.lang.IllegalArgumentException
2022-09-29 14:33:19.120 26163-26921/com.tencent.qgame.playerproj I/AnimSimpleDemoActivity: onFailed errorType=10002 errorMsg=0x2 MediaCodec exception e=java.lang.IllegalArgumentException

**Comment by hexleo** [comment]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/3285051/192965401-5b5530e9-cf8d-4d2e-b247-173e26b3f1f7.png">
你没实现这个日志接口吗？这个日志接口会打印vap内部的一些日志

你在Android 的Demo上运行看看，里边有打日志，而且也可以和你app里进行对比看看是不是都是必现的
